### ISSUE TITLE
Elder registration

### ISSUE THREAD

**Issue by roy-shchory** [TechnionYP5777/SmartCity-Elderly-Support#16]
A new elder will be registered in the system by the admins. 
registration info:
- General info (name, age, id)
- Info of family or other contacts
- House info (address, rooms info)
- Sensors setup (kind of sensors and locations)

**Comment by inbalzukerman** [comment]
Since this issue was opened a while ago I'll summarize the currently required functionalities:

- [ ] "Register" the client and save the necessary data
- [ ] Present general Information about the elderly 
- [ ] Present information about client's emergency contacts
- [ ] Edit \ register emergency contacts
