### ISSUE TITLE
Establish database system 

### ISSUE THREAD

**Issue by inbalzukerman** [TechnionYP5777/SmartCity-Elderly-Support#24]
for more info: #16 , #19 

Required functionalities:
* initialize the database
* update the database
* receive information from the database
* etc.

**Comment by inbalzukerman** [comment]
TODO:
* Create the "System Package"
* Create the "Database" class in the "System" package and implement it.

**Comment by EliaTraore** [comment]
Please implement DatabaseHandlerAPI interface (i think it belongs under this issue), its the required functionality by the ApplicationHandler in order to access the info stored in the system.
The interface itself isn't important and can be deleted after its functions are implemented and all calls to the interface are replaced by calls to the concrete implementation.

**Comment by inbalzukerman** [comment]
@EliaTraore - will do asap 👍  Unfortunately it will be only later today

**Comment by inbalzukerman** [comment]
Relevant issues have been opened and all tasks have been assigned. This issue is unnecessary anymore 😄
